services:
  - docker:dind

stages:
  - build

build-master:
  stage: build
  retry: 0
  image: docker:20
  before_script:
    - cd bazel_docker_container
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export IMAGE_SUFFIX=$(basename $(pwd))
    - echo "IMAGE_SUFFIX=${IMAGE_SUFFIX}"
    - export DOCKER_IMAGE=${CI_REGISTRY_IMAGE}/${IMAGE_SUFFIX}
    - echo "DOCKER_IMAGE=${DOCKER_IMAGE}"
  script:
    - docker pull $DOCKER_IMAGE:stable || true
    - >
      docker build
      --pull
      --cache-from $DOCKER_IMAGE:stable
      --tag $DOCKER_IMAGE:latest
      --tag $DOCKER_IMAGE:stable
      .
    - docker push $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:stable
  only:
    - master
